### ISSUE TITLE
WSA startup

### ISSUE THREAD

**Issue by kojiba** [JuNijland/feathernet#1]
If created more than 1 server, WSAStartup will be called many times. "src/server.c"
# ifdef OS_WINDOWS

```
WSADATA wsa;
if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) {
    FEATHER_DBG_PRINT(("ERROR: Failed to initialize Winsock2;"
            "err_code: %d\n", WSAGetLastError()));
    return -1;
}
```
# endif

You may create flag for check if already inited.

**Comment by JuNijland** [comment]
Ah I see, I quickly implemented support for windows without looking to much into it. I will change it asap, thanks for the heads up!
